name: LCTIMSpy
channels:
  - conda-forge
  - schrodinger
  - defaults
dependencies:
 - pip:
      - alphatims==1.0.8
      - altgraph==0.17.4
      - bokeh==3.6.0
      - cairocffi==1.7.1
      - click==8.1.7
      - colorcet==3.1.0
      - contourpy==1.3.0
      - cycler==0.12.1
      - dill==0.3.8
      - et-xmlfile==2.0.0
      - fonttools==4.54.1
      - greenlet==3.1.0
      - holoviews==1.19.1
      - hvplot==0.11.1
      - idna==3.8
      - kiwisolver==1.4.7
      - lc-cid-tims-analysis==0.1.0
      - linkify-it-py==2.0.3
      - llvmlite==0.43.0
      - lxml==5.3.0
      - markdown==3.7
      - markdown-it-py==3.0.0
      - matplotlib==3.9.2
      - mdit-py-plugins==0.4.2
      - mdurl==0.1.2
      - multiprocess==0.70.16
      - narwhals==1.32.0
      - numba==0.60.0
      - numpy==2.2.0
      - openpyxl==3.1.5
      - pandas==2.2.2
      - panel==1.5.3
      - param==2.1.1
      - patsy==1.0.1
      - pefile==2024.8.26
      - pillow==11.0.0
      - pip-licenses==5.0.0
      - plotly==6.0.1
      - prettytable==3.11.0
      - psims==1.3.4
      - pybaf2sql==0.2.2
      - pydub==0.25.1
      - pyimzml==1.5.1+gtluu.2
      - pyinstaller==6.10.0
      - pyinstaller-hooks-contrib==2024.8
      - pyparsing==3.2.0
      - pyside6==6.7.2
      - pyside6-addons==6.7.2
      - pyside6-essentials==6.7.2
      - pytdfsdk==0.4.1
      - pyteomics==4.7.5
      - pytz==2024.2
      - pyviz-comms==3.0.3
      - pywin32-ctypes==0.2.3
      - pyzstd==0.16.2
      - scipy==1.14.1
      - seaborn==0.13.2
      - shiboken6==6.7.2
      - sqlalchemy==2.0.34
      - statannotations==0.7.2
      - statsmodels==0.14.4
      - timsconvert==2.0.0
      - tomli==2.0.2
      - tqdm==4.66.5
      - typing-extensions==4.12.2
      - tzdata==2024.1
      - uc-micro-py==1.0.3
      - wcwidth==0.2.13
      - wheezy-template==3.2.2
      - xyzservices==2024.9.0
